version: "3"
services:
  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "./wordpress:/var/www/html"

  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    env_file:
      - ".env"
    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - "./mariadb_data:/bitnami/mariadb"
    ports:
      - "3366:3306"
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
  phpmyadmin:
    image: "docker.io/bitnami/phpmyadmin:5-debian-10"
    ports:
      - "8080:8080"
      - "4433:8443"
    depends_on:
      - mariadb
  wordpress:
    image: wordpress
    container_name: wordpress_pro
    links:
      - mariadb:mysql
    environment:
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DEBUG=true
    ports:
      - "8866:80"
    volumes:
      - ./wordpress:/var/www/html:rw,delegated
#####COMPOSER
# composer:
#     image: "composer"
#     volumes:
#         - "./web/app:/app"
#     command: install
#####OTHER MYPHPADMIN
#   myadmin:
#     image: phpmyadmin/phpmyadmin
#     container_name: phpmyadmin
#     ports:
#       - "8080:80"
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_HOST=${MYSQL_HOST}
#     restart: always
#     depends_on:
#       - mariadb
#####MYSQL
#   mysqldb:
#     image: mysql:${MYSQL_VERSION}
#     container_name: ${MYSQL_HOST}
#     restart: always
#     env_file:
#       - ".env"
#     environment:
#       - MYSQL_DATABASE=${MYSQL_DATABASE}
#       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#       - MYSQL_USER=${MYSQL_USER}
#       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#     ports:
#       - "3306:3306"
#     volumes:
#       - "./data/db/mysql:/var/lib/mysql"
#####NGINX
#   web:
#     image: nginx:alpine
#     volumes:
#       - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
#       - "./etc/ssl:/etc/ssl"
#       - "./wordpress:/var/www/html"
#       - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
#     ports:
#       - "8000:80"
#       - "3000:443"
#     environment:
#       - NGINX_HOST=${NGINX_HOST}
#     command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#     restart: always
#     depends_on:
#       - php
#       - mariadb
